### ISSUE TITLE
Doesn't handle parameters in my rails

### ISSUE THREAD

**Issue by ndvbd** [ahorek/terser-ruby#12]
in production.rb I added:

Sprockets.register_compressor 'application/javascript', :terser, Terser::Compressor

and also inside the configure do i did:

config.assets.js_compressor = Terser.new(:mangle => false, :compress => false)

but it still compress the asset, and changing the parameters does nothing....

**Comment by ahorek** [comment]
hi @ndvbd !
compress => false disables all code optimizations, but whitespace removal is still active. This is intentional.

If you want to skip the minification for some environments, just don't assign the config.assets.js_compressor at all. Or why do you want to skip compression?
