### ISSUE TITLE
Lock ExecJS to 2.7.0

### ISSUE THREAD

**Issue by kylazath** [ahorek/terser-ruby#22]
Hello there.

Recent update bumped ExecJS to 2.8.x, which causes crashes. Shouldn't it be locked at 2.7.0?
Please take a look at an [ExecJS issue](https://github.com/rails/execjs/issues/99).

**Comment by ahorek** [comment]
this gem is tested with execjs 2.8.x, see builds https://github.com/ahorek/terser-ruby/runs/2924745618

as far as I see, the error is related to https://github.com/ai/autoprefixer-rails .

if you still think the error somehow related to this library, please let me know.
